### ISSUE TITLE
Add presse.html

### ISSUE THREAD

**Issue by benjaminpreiss** [benjaminpreiss/susanne_preiss_website#40]
New page called **presse.html**

**Comment by benjaminpreiss** [comment]
@bxandre Not yet ;) Es fehlen noch ein/zwei kleine Dinge...

**Comment by benjaminpreiss** [comment]
### Badisches Tageblatt
Susanne Preiss gehört der Jury des Gala Spa Awards an…
### Business Traveller
„Ich muss nicht immer erreichbar sein...“
### emotion
Alles braucht so lange, bis es fertig ist…?
### emotion slow
Vier Generationen von Frauen über gutes und schlechtes Tempo in ihrem Leben…
### Financial Times
Susanne Preiss lehrt Stressgeplagte zu „entschleunigen“...
### Madame
Dass dauerhafter Stress krank machen kann, ist bekannt…
### NZZ Neue Zürcher Zeitung
Innere Ruhe sorgt für äußere Spannkraft...
### Stern
Das Gefühl, immer schneller leben zu müssen, macht uns krank. Langsam wächst
die Erkenntnis, dass es so nicht weitergehen kann...
### Süddeutsche Zeitung
### Welt Kompakt
Stille, Entspannung und wohltuende Langsamkeit: Ein Wochenende im Kloster
Plankstetten...
### Welt Am Sonntag
Die Entdeckung der Langsamkeit. "Entschleunigung" ist das Gebot der nur scheinbar
nicht vorhandenen Zeit...
### Rheinische Post
Freudlose Schweißtreiberei schadet doch nur...
### Für Sie
Ich atme hektisch ein und viel zu schnell aus – nichts fließt....
### manager Seminare
Der Job wird immer härter. Das Tempo zieht an, der wirtschaftliche Druck steigt...
### Praxis Magazin
Workout und Entspannung – das perfekte Stressmanagement...
### QiGong
90% aller Arbeitnehmer haben das Gefühl, keine Zeit mehr zu haben: „Hurry
Sickness“...
### Taunus BKK
Die Welt dreht sich immer schneller. Mit Mini-Meditation zur Ruhe kommen...
### Weser Kurier
Wenn der Garten auf einmal ganz anders aussieht. Susanne Preiss gibt
Entschleunigungskurse...
### Shape
Es ist Muskeltraining. Es ist Meditation. Es ist Medizin. Qi Gong...

**Comment by benjaminpreiss** [comment]
@bxandre Susi hat mir heute den Süddeutsche Zeitung Text geliefert. Schicke dir den gleich zu.

**Comment by benjaminpreiss** [comment]
Implementation steps:

- [ ] Setup html markup
- [ ] Attach pdfs to html markup
- [ ] Set proper backgrounds to each article

**Comment by benjaminpreiss** [comment]
@bxandre hier die mobile ansicht...
![image](https://user-images.githubusercontent.com/28349122/87555659-0b0d7400-c6b6-11ea-9410-425177d4dc0e.png)
Wollen wir eventuell die headline weglassen und dafür den text unten zentrieren?

**Comment by bxandre** [comment]
„Headline“ kannst Du nicht weglassen, keiner weiß, das BT das „Badische Tageblatt“ ist.
Mittig fände ich ok. Zumindest in der mobilen Ansicht. 

Desktop lieber bei unserer Variante bleiben.
Die hast du doch, oder…?



--------------------------------------------------
baxmann kommunikation gmbh  
ballindamm 15 / 20095 hamburg 
germany     

t +49 (40) 41 35 21 05
f +49 (40) 41 35 21 08
m +49 171 69 28 470

andre@baxmann.net
http://www.baxmann.net
--------------------------------------------------

**Comment by benjaminpreiss** [comment]
Ja, die habe ich :)

**Comment by benjaminpreiss** [comment]
@bxandre 

Mobile Ansicht:

![image](https://user-images.githubusercontent.com/28349122/87639292-502cb700-c745-11ea-9c9e-e2685bf11195.png)

Desktop Ansicht:

![image](https://user-images.githubusercontent.com/28349122/87639353-6b97c200-c745-11ea-8a09-7f82ecf85a86.png)

**Comment by bxandre** [comment]
gut, ok

--------------------------------------------------
baxmann kommunikation gmbh  
ballindamm 15 / 20095 hamburg 
germany     

t +49 (40) 41 35 21 05
f +49 (40) 41 35 21 08
m +49 171 69 28 470

andre@baxmann.net
http://www.baxmann.net
--------------------------------------------------
