### ISSUE TITLE
Add favicon to all pages

### ISSUE THREAD

**Issue by benjaminpreiss** [benjaminpreiss/susanne_preiss_website#42]

**Comment by benjaminpreiss** [comment]
1) Upload der Bilddateien
Laden Sie alle Bilddateien in das Root Verzeichnis ihrer Domain

2) HTML Codes einfügen
Fügen Sie den folgenden HTML Code zwischen den beiden `<head> </head>` Tags ein:

```html
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
```

**Comment by benjaminpreiss** [comment]
- [ ] Add new copyPlugin entry in webpack production and development.

**Comment by benjaminpreiss** [comment]
@bxandre Hey, wollen wir die Ecken vom favicon eventuell rund machen? Sieht vielleicht besser aus...

**Comment by bxandre** [comment]
try...

sent from a mobile device, somewhere in the desolated backwater

**Comment by benjaminpreiss** [comment]
@bxandre Könntest du Thomas fragen, ob er mir das schicken kann? Er hat da wohl irgendwie so einen fancy favicon generator benutzt mit dem er mir alle favicon files zusammen gestellt hat

**Comment by bxandre** [comment]
was genau schicken?

--------------------------------------------------
baxmann kommunikation gmbh  
ballindamm 15 / 20095 hamburg 
germany     

t +49 (40) 41 35 21 05
f +49 (40) 41 35 21 08
m +49 171 69 28 470

andre@baxmann.net
http://www.baxmann.net
--------------------------------------------------

**Comment by bxandre** [comment]
habe ich mir im Original angesehen, sieht doch gut aus.

**Comment by bxandre** [comment]
habe mir auch Presse angesehen, auch super :-)
