### ISSUE TITLE
New layout articles

### ISSUE THREAD

**Issue by benjaminpreiss** [benjaminpreiss/susanne_preiss_website#43]
![image](https://user-images.githubusercontent.com/28349122/87546786-66d20000-c6aa-11ea-920e-f0b7dee623ae.png)

**Comment by benjaminpreiss** [comment]
@bxandre Was denkst du? Ich hab mal ein bisschen rumgespielt und finde, dass es so wie im bild oben auch ganz gut aussieht.

Also wenn titel, überschrift und link nebeneinander stehen.

**Comment by bxandre** [comment]
…versteh ich nicht ganz. Ist das die Mobil-Darstellung?
Ich seh es hier mal mit, mal ohne Logo?
 
Wir hatten übrigens die Logos alle auf weiß, aber das muss nicht unbedingt sein. 
Textblöcke müssen aber linksbündig, schön einen über dem anderen, das ist allerdings wichtig.

Gruß André



--------------------------------------------------
baxmann kommunikation gmbh  
ballindamm 15 / 20095 hamburg 
germany     

t +49 (40) 41 35 21 05
f +49 (40) 41 35 21 08
m +49 171 69 28 470

andre@baxmann.net
http://www.baxmann.net
--------------------------------------------------

**Comment by benjaminpreiss** [comment]
Hey Andre, das ist ja der Hammer! Langsam kommst du rein :)

Ich habe eben mal weiter rumgesponnen und jetzt sieht es so aus:

![image](https://user-images.githubusercontent.com/28349122/87548909-743cb980-c6ad-11ea-9ef0-c84b3842953f.png)

Referenz ist dabei nur der oberste Artikel. Der Rest stimmt noch nicht.

Passt das so?

**Comment by benjaminpreiss** [comment]
Bezüglich des weißen Hintergrund: den werde ich rausnehmen wo es gut aussieht...

**Comment by bxandre** [comment]
ok, verstehe ich. Nimme den weißen Untergrund überall raus. Hast recht!

--------------------------------------------------
baxmann kommunikation gmbh  
ballindamm 15 / 20095 hamburg 
germany     

t +49 (40) 41 35 21 05
f +49 (40) 41 35 21 08
m +49 171 69 28 470

andre@baxmann.net
http://www.baxmann.net
--------------------------------------------------

**Comment by benjaminpreiss** [comment]
Closing issue. Not implemented
