### ISSUE TITLE
Make fonts bigger

### ISSUE THREAD

**Issue by benjaminpreiss** [benjaminpreiss/susanne_preiss_website#5]
Textgrößen: würde ich insgesamt etwas größer machen. Viel wird sich ja auch über das smart phone abspielen.
Lauftexte einfach insgesamt etwas größer, Headlines würde ich in identischer Größe zu den Schlagworten der homepage setzen.

**Comment by benjaminpreiss** [comment]
@bxandre besteht dieses Problem nach wie vor noch für dich?

**Comment by bxandre** [comment]
?
welches Problem?

--------------------------------------------------
baxmann kommunikation gmbh  
ballindamm 15 / 20095 hamburg 
germany     

t +49 (40) 41 35 21 05
f +49 (40) 41 35 21 08
m +49 171 69 28 470

andre@baxmann.net
http://www.baxmann.net
--------------------------------------------------

**Comment by benjaminpreiss** [comment]
Closing issue now.
